cargo-features = ["edition"]

[package]
name = "lodestone_api"
version = "0.1.0"
authors = ["Kyle Clemens <git@kyleclemens.com>"]

edition = "2018"

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
